# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cleanslate < Formula
  desc "Clean your Kubernetes cluster"
  homepage "https://github.com/sreeram-venkitesh/homebrew-cleanslate"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sreeram-venkitesh/cleanslate/releases/download/v0.1.2/cleanslate_Darwin_arm64.tar.gz"
      sha256 "3e8d153664fe2bda61e8110160d690f5427ec4e39e4cc49782be5b3ece57aeb5"

      def install
        bin.install "cleanslate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sreeram-venkitesh/cleanslate/releases/download/v0.1.2/cleanslate_Darwin_x86_64.tar.gz"
      sha256 "86fd8d07c5eb2e9045e186aaa88de278a492f58a63bdee966def0b5e3c5d08fc"

      def install
        bin.install "cleanslate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sreeram-venkitesh/cleanslate/releases/download/v0.1.2/cleanslate_Linux_arm64.tar.gz"
      sha256 "848141d8328006dc9a31d2691f27f28c828a54eeb2e3403becb8dd0bd926428d"

      def install
        bin.install "cleanslate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sreeram-venkitesh/cleanslate/releases/download/v0.1.2/cleanslate_Linux_x86_64.tar.gz"
      sha256 "74572d86d0e02424c53620c94a5e0b949a692b6e08381f7f55dcb39f18457e0f"

      def install
        bin.install "cleanslate"
      end
    end
  end
end
